name: Kubectl get nodes

on: 
    push:
    #workflow_dispatch:
            

jobs:  
          
    deploy_using_argo:
        runs-on: self-hosted
        steps:
            - name: Deploy the kube app
              run: |
                argocd app create vote-kodu \
                  --repo https://github.com/rjain997/k8s
                  --path k8s-specifications \
                  --dest-server https://kubernetes.default.svc \
                  --dest-namespace voting \
                  --sync-policy automated                    